# Generated by Django 2.2.19 on 2021-02-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass_things_app', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
